Add support for msdd6000 with resampler in FPGA.

diff --git a/gr-msdd6000/src/Makefile.swig.gen b/gr-msdd6000/src/Makefile.swig.gen
--- a/gr-msdd6000/src/Makefile.swig.gen
+++ b/gr-msdd6000/src/Makefile.swig.gen
@@ -33,14 +33,21 @@
 ## this has to be done in the including Makefile.am -before-
 ## Makefile.swig is included.
 
+
 msdd_pythondir_category ?= gnuradio/msdd
 msdd_pylibdir_category ?= $(msdd_pythondir_category)
 msdd_pythondir = $(pythondir)/$(msdd_pythondir_category)
 msdd_pylibdir = $(pyexecdir)/$(msdd_pylibdir_category)
 
+msdd_rs_pythondir_category ?= gnuradio/msdd_rs
+msdd_rs_pylibdir_category ?= $(msdd_rs_pythondir_category)
+msdd_rs_pythondir = $(pythondir)/$(msdd_rs_pythondir_category)
+msdd_rs_pylibdir = $(pyexecdir)/$(msdd_rs_pylibdir_category)
+
 ## SWIG headers are always installed into the same directory.
 
 msdd_swigincludedir = $(swigincludedir)
+msdd_rs_swigincludedir = $(swigincludedir)
 
 ## This is a template file for a "generated" Makefile addition (in
 ## this case, "Makefile.swig.gen").  By including the top-level
@@ -63,6 +70,7 @@ msdd_swigincludedir = $(swigincludedir)
 ## the SWIG-generated files will be removed from the distribution.
 
 STAMPS += $(DEPDIR)/msdd-generate-*
+STAMPS += $(DEPDIR)/msdd_rs-generate-*
 
 ## Other cleaned files: dependency files generated by SWIG or this Makefile
 
@@ -72,26 +80,39 @@ MOSTLYCLEANFILES += $(DEPDIR)/*.S*
 ## .h file is sometimes built, but not always ... so that one has to
 ## be added manually by the including Makefile.am .
 
-swig_built_sources += msdd.py msdd.cc
+swig_built_sources += msdd.py msdd_rs.py msdd.cc msdd_rs.cc
 
 ## Various SWIG variables.  These can be overloaded in the including
 ## Makefile.am by setting the variable value there, then including
 ## Makefile.swig .
 
 msdd_swiginclude_HEADERS =		\
-	msdd.i			\
+	msdd.i				\
+	msdd_rs.i			\
 	$(msdd_swiginclude_headers)
 
 msdd_pylib_LTLIBRARIES =		\
 	_msdd.la
 
+msdd_rs_pylib_LTLIBRARIES =		\
+        _msdd_rs.la
+
 _msdd_la_SOURCES = 			\
-	msdd.cc			\
+	msdd.cc				\
 	$(msdd_la_swig_sources)
+
+_msdd_rs_la_SOURCES =          		\
+    msdd_rs.cc         			\
+    $(msdd_la_swig_sources)
+
 
 _msdd_la_LIBADD =			\
 	$(STD_SWIG_LA_LIB_ADD)		\
 	$(msdd_la_swig_libadd)
+
+_msdd_rs_la_LIBADD =           		\
+    $(STD_SWIG_LA_LIB_ADD)      	\
+    $(msdd_rs_la_swig_libadd)
 
 _msdd_la_LDFLAGS =			\
 	$(STD_SWIG_LA_LD_FLAGS)		\
@@ -101,9 +122,21 @@ _msdd_la_CXXFLAGS =			\
 	$(STD_SWIG_CXX_FLAGS)		\
 	$(msdd_la_swig_cxxflags)
 
+_msdd_rs_la_LDFLAGS =          		\
+    $(STD_SWIG_LA_LD_FLAGS)     	\
+    $(msdd_rs_la_swig_ldflags)
+
+_msdd_rs_la_CXXFLAGS =         		\
+    $(STD_SWIG_CXX_FLAGS)       	\
+    $(msdd_rs_la_swig_cxxflags)
+
 msdd_python_PYTHON =			\
-	msdd.py			\
+	msdd.py				\
 	$(msdd_python)
+
+msdd_rs_python_PYTHON =		        \
+    msdd_rs.py         			\
+    $(msdd_rs_python)
 
 ## Entry rule for running SWIG
 
@@ -251,9 +284,161 @@ $(DEPDIR)/msdd-generate-stamp:
 ##
 	touch $(DEPDIR)/msdd-generate-stamp
 
+
+
+
+
+
+msdd_rs.h msdd_rs.py msdd_rs.cc: msdd_rs.i
+## This rule will get called only when MAKE decides that one of the
+## targets needs to be created or re-created, because:
+##
+## * The .i file is newer than any or all of the generated files;
+##
+## * Any or all of the .cc, .h, or .py files does not exist and is
+##   needed (in the case this file is not needed, the rule for it is
+##   ignored); or
+##
+## * Some SWIG-based dependecy of the .cc file isn't met and hence the
+##   .cc file needs be be regenerated.  Explanation: Because MAKE
+##   knows how to handle dependencies for .cc files (regardless of
+##   their name or extension), then the .cc file is used as a target
+##   instead of the .i file -- but with the dependencies of the .i
+##   file.  It is this last reason why the line:
+##
+##     	if test -f $@; then :; else
+##
+##   cannot be used in this case: If a .i file dependecy is not met,
+##   then the .cc file needs to be rebuilt.  But if the stamp is newer
+##   than the .cc file, and the .cc file exists, then in the original
+##   version (with the 'test' above) the internal MAKE call will not
+##   be issued and hence the .cc file will not be rebuilt.
+##
+## Once execution gets to here, it should always proceed no matter the
+## state of a stamp (as discussed in link above).  The
+## $(DEPDIR)/msdd-generate stuff is used to allow for parallel
+## builds to "do the right thing".  The stamp has no relationship with
+## either the target files or dependency file; it is used solely for
+## the protection of multiple builds during a given call to MAKE.
+##
+## Catch signals SIGHUP (1), SIGINT (2), SIGPIPE (13), and SIGTERM
+## (15).  At a caught signal, the quoted command will be issued before
+## exiting.  In this case, remove any stamp, whether temporary of not.
+## The trap is valid until the process exits; the process includes all
+## commands appended via "\"s.
+##
+	trap 'rm -rf $(DEPDIR)/msdd_rs-generate-*' 1 2 13 15; \
+##
+## Create a temporary directory, which acts as a lock.  The first
+## process to create the directory will succeed and issue the MAKE
+## command to do the actual work, while all subsequent processes will
+## fail -- leading them to wait for the first process to finish.
+##
+	if mkdir $(DEPDIR)/msdd_rs-generate-lock 2>/dev/null; then \
+##
+## This code is being executed by the first process to succeed in
+## creating the directory lock.
+##
+## Remove the stamp associated with this filename.
+##
+		rm -f $(DEPDIR)/msdd_rs-generate-stamp; \
+##
+## Tell MAKE to run the rule for creating this stamp.
+##
+		$(MAKE) $(AM_MAKEFLAGS) $(DEPDIR)/msdd_rs-generate-stamp WHAT=$<; \
+##
+## Now that the .cc, .h, and .py files have been (re)created from the
+## .i file, future checking of this rule during the same MAKE
+## execution will come back that the rule doesn't need to be executed
+## because none of the conditions mentioned at the start of this rule
+## will be positive.  Remove the the directory lock, which frees up
+## any waiting process(es) to continue.
+##
+		rmdir $(DEPDIR)/msdd_rs-generate-lock; \
+	else \
+##
+## This code is being executed by any follower processes while the
+## directory lock is in place.
+##
+## Wait until the first process is done, testing once per second.
+##
+		while test -d $(DEPDIR)/msdd_rs-generate-lock; do \
+			sleep 1; \
+		done; \
+##
+## Succeed if and only if the first process succeeded; exit this
+## process returning the status of the generated stamp.
+##
+		test -f $(DEPDIR)/msdd_rs-generate-stamp; \
+		exit $$?; \
+	fi;
+
+$(DEPDIR)/msdd_rs-generate-stamp:
+## This rule will be called only by the first process issuing the
+## above rule to succeed in creating the lock directory, after
+## removing the actual stamp file in order to guarantee that MAKE will
+## execute this rule.
+##
+## Call SWIG to generate the various output files; special
+## post-processing on 'mingw32' host OS for the dependency file.
+##
+	if $(SWIG) $(STD_SWIG_PYTHON_ARGS) $(msdd_rs_swig_args) \
+		-MD -MF $(DEPDIR)/msdd_rs.Std \
+		-module msdd_rs -o msdd_rs.cc $(WHAT); then \
+	    if test $(host_os) = mingw32; then \
+		$(RM) $(DEPDIR)/msdd_rs.Sd; \
+		$(SED) 's,\\\\,/,g' < $(DEPDIR)/msdd_rs.Std \
+			> $(DEPDIR)/msdd_rs.Sd; \
+		$(RM) $(DEPDIR)/msdd_rs.Std; \
+		$(MV) $(DEPDIR)/msdd_rs.Sd $(DEPDIR)/msdd_rs.Std; \
+	    fi; \
+	else \
+	    $(RM) $(DEPDIR)/msdd_rs.S*; exit 1; \
+	fi;
+##
+## Mess with the SWIG output .Std dependency file, to create a
+## dependecy file valid for the input .i file: Basically, simulate the
+## dependency file created for libraries by GNU's libtool for C++,
+## where all of the dependencies for the target are first listed, then
+## each individual dependency is listed as a target with no further
+## dependencies.
+##
+## (1) remove the current dependency file
+##
+	$(RM) $(DEPDIR)/msdd_rs.d
+##
+## (2) Copy the whole SWIG file:
+##
+	cp $(DEPDIR)/msdd_rs.Std $(DEPDIR)/msdd_rs.d
+##
+## (3) all a carriage return to the end of the dependency file.
+##
+	echo "" >> $(DEPDIR)/msdd_rs.d
+##
+## (4) from the SWIG file, remove the first line (the target); remove
+##     trailing " \" and " " from each line.  Append ":" to each line,
+##     followed by 2 carriage returns, then append this to the end of
+##     the dependency file.
+##
+	$(SED) -e '1d;s, \\,,g;s, ,,g' < $(DEPDIR)/msdd_rs.Std | \
+		awk '{ printf "%s:\n\n", $$0 }' >> $(DEPDIR)/msdd_rs.d
+##
+## (5) remove the SWIG-generated file
+##
+	$(RM) $(DEPDIR)/msdd_rs.Std
+##
+## Create the stamp for this filename generation, to signal success in
+## executing this rule; allows other threads waiting on this process
+## to continue.
+##
+	touch $(DEPDIR)/msdd_rs-generate-stamp
+
 # KLUDGE: Force runtime include of a SWIG dependency file.  This is
 # not guaranteed to be portable, but will probably work.  If it works,
 # we have accurate dependencies for our swig stuff, which is good.
 
+
 @am__include@ @am__quote@./$(DEPDIR)/msdd.d@am__quote@
+@am__include@ @am__quote@./$(DEPDIR)/msdd_rs.d@am__quote@
+
 
